main:
  - identifier: ai
    name: AI Solutions
    url: /ai
    weight: 100
  - identifier: consultancy
    name: Consultancy
    url: /consultancy
    weight: 200
  - identifier: staff-augmentation
    name: Staff Augmentation
    url: /staff-augmentation
    weight: 300